PA2Seq: proj2Seq.c
	mpicc -lpmi -o PA2Seq proj2Seq.c

PA2DPar: proj2DPar.c
	mpicc -lpmi -o PA2DPar proj2DPar.c

PA2SPar: proj2SPar.c
	mpicc -lpmi -o PA2SPar proj2SPar.c

clean:
	$(RM) PA2Seq PA2DPar PA2SPar
