PA2Seq: proj2Seq.c
	mpicc -lpmi -o proj2Seq proj2Seq.c

PA2DPar: proj2DynPar.c
	mpicc -lpmi -o proj2DPar proj2Par.c

PA2SPar: proj2StatPar.c
	mpicc -lpmi -o proj2SPar proj2Par.c

clean:
	$(RM) proj2Seq proj2DPar proj2SPar
